---
- name: Ensure iTerm directories are initialized if they are not already.
  command: "open -a /Applications/iTerm.app"
  args:
    creates: "~/Library/Application Support/iTerm2/DynamicProfiles/"

- name: Ensure fonts are installed.
  get_url:
    url: "{{ item.url }}"
    dest: "~/Library/Fonts"
  with_items: "{{ iterm2_fonts }}"
  when: iterm2_fonts is defined

- name: Ensure DynamicProfiles are installed.
  uri:
    url: "{{ item.url }}"
    dest:  "~/Library/Application Support/iTerm2/DynamicProfiles/"
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    force_basic_auth: yes
  with_items: "{{ iterm2_dynamic_profiles }}"
  when: iterm2_dynamic_profiles is defined

- name: Ensure preferences are loaded from a custom folder.
  command: "defaults write com.googlecode.iterm2 'PrefsCustomFolder' -string '{{ iterm2_preferences_custom_folder }}'"
  when: iterm2_preferences_custom_folder is defined and iterm2_preferences_custom_folder

# If loading preferences from a folder, user probably shouldn't set this.
- name: Ensure configured profile is set to default.
  command: "defaults write com.googlecode.iterm2 'Default Bookmark Guid' -string '{{ iterm2_default_profile_guid }}'"
  when: iterm2_default_profile_guid is defined and iterm2_default_profile_guid

- name: Ensure shell integration is installed.
  shell: curl -L https://iterm2.com/misc/install_shell_integration.sh | bash
  args:
    warn: no
  when: iterm2_shell_integration is defined and iterm2_shell_integration
